name: CI
on: [push]
jobs:
  yaml-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: pip install yamllint

      - name: Lint
        run: yamllint --strict -c yamllint.yaml .
